# I Introducción {.unnumbered}

Este primer reporte trimestral, reporta las metas alcanzadas durante el periodo enero - marzo 2024, en el marco de los resultados del Contrato de Administración del Parque Nacional Cordillera Azul (CdA PNCAZ). En este se detallen las actividades y resultados obtenidos, de acuerdo con el programa quinquenal 2024 – 2028. A continuación, se detallan los resultados más importantes obtenidos en el trimestre.

### **Resultado 1**

Este primer trimestre, se realizaron 186 patrullajes; 168 rutinarios y 18 especiales, en los 22 puestos de vigilancia (@tbl-npat). De igual manera, a la fecha se cuenta con 61 casos presentados a la Fiscalía Especializada en Materia Ambiental (FEMA), vigentes y en etapa de investigación (@fig-apoyolegal).

Además, 97 personas de 8 comunidades nativas y 28 centros poblados participaron en la vigilancia comunal (@fig-dist), junto con los guardaparques. La inversión realizada total, por este apoyo comunal fue de S/.62, 868 (@fig-apoyo), sólo en este primer trimestre; de los cuales 30 fueron mujeres y 67 varones (@fig-sexo).

El estado de conservación de la cobertura de bosque dentro del Parque, se mantiene intacta; en 1, 353, 141.06 hectáreas. Asimismo; 49.57 ha., se encuentran en recuperación dentro del parque; pues fueron afectadas por tala selectiva, extracción de madera y actividades ganaderas, que actualmente están controladas (@fig-ganadero,@fig-palomar). Además, se reportó 316.87 ha., de perdida natural de bosque.

En la zona de amortiguamiento, 824.50 ha., de bosque fueron deforestados; siendo afectados 16 de los 18 sectores críticos de vigilancia; entre los anillos 1 y 5 km del parque. Los sectores críticos de vigilancia más afectados fueron los sectores Santa Ana, Ipururo, Pólvora y Shapaja. Además, fueron aperturados 6.39 km de trochas, en los sectores de Shapaja (4.52 km) y Santa Ana (1.87 km).

Las alerta de focos de calor disminuyeron 35% en comparación con el último trimestre 2023. Se registraron 816 alertas en la ZA del parque, de las cuales 30 fueron detectadas en el anillo 1 y 5 km. Ninguna alerta de foco de calor fue detectada dentro del parque (@fig-focos).

Fueron realizados dos capacitaciones a los guardaparques, especialistas y técnicos de CIMA y SERNANP. La primera sobre primeros auxilios, uso y manipulación de suero antiofidico. La segunda fue un reforzamiento sobre los conocimientos teóricos y prácticos de la herramienta SMART mobile (@fig-capsmart).

Respecto de las opiniones técnicas que realiza el Parque, 132 solicitudes fueron atendidas. Cuatro de estas opiniones fueron categorizadas con un impacto Alto (@fig-apoyolegal).

Para este trimestre, la sede de Tarapoto CIMA continúa con la atención en el mantenimiento y refacciones de los Puestos de Vigilancia. Así como el equipamiento del personal guardaparque.

CIMA también apoya la instalación de letreros informativos comunales en la ZA del parque. Al trimestre 2024, se tienen instalados 36 letreros informativos; distribuidos en las cuatros sedes de intervención del proyecto (@fig-LIL).

Cuatro comunidades nativas de las etnias Kichwa, Shipibo-Konibo y Yine, y cinco centros poblados, han desarrollado con libertad sus actividades de subsistencia mediante la cacería y pesca, dentro del Parque. El promedio de edad de las personas que ingresan al parque, estuvo en un rango de 36 \~ 31 años; de 41 personas (@fig-procedencia).

Los mamíferos obtenidos por la cacería suman 507 kg y fueron los más aprovechados; siendo el Majaz el más aprovechado (358 kg). Mientra que, las aves y peces; Pucacunga (5kg) y Carachama (44 kg), respectivamente, fueron aprovechados en menor cantidad (@fig-especies_uso).

En relación a los registros de fauna, se registraron 230 especies, en los 21 sectores de vigilancia y control del parque (@fig-abundancia). De las cuales, 40 fueron plenamente identificadas con nombre científico y representan las especies más comunes de los registros, por ejemplo (@fig-fauna_puestos). Resaltan los registros de especies amenazadas y cuya presencia alienta la conservación del parque; ”Perro de Monte” Speothos venaticus, “Carachupa mama” Priodontes maximus, Puma concolor, “Oso de anteojos” Tremactos ornatus, “Tigrillo” Leopardus pardalis y “Maquizapa” Ateles chamek.

### **Resultado 2**

Este trimestre, se comenzó con la evaluación de áreas prioritarias de investigación; que orientarán el desarrollo de investigaciones en las áreas de ecológica y conservación, medio ambiente y sociología, entre los principales. Además, se ha evaluado las iniciativas de conservación, que serán priorizadas para desarrollar una línea base de diversidad (@fig-iniciativas), que contribuirán a fortalecer la información científica para el turismo, así como su importancia para la conservación de especies.

Trabajos de investigación desarrollados por CIMA, dentro del Parque. A la fecha, CIMA, viene desarrollando una investigación sobre "Regeneración Natural del Bosque, dentro de áreas que fueron previamente deforestadas, en el sector Palomar-Shanshuico” y “Dinámica del bosque en el sector Chambirillo". Ambas investigaciones se encuentran en etapa de análisis de información.

Elaboración de una ficha técnica técnica del “Boquichico” Prochilodus nigricans. Se concluyó que el “Boquichico” es importante en la alimentación de las comunidades asentadas entre los ríos Cushabatay y Pisqui. Además, estos lugares son claves, para la reproducción y migración de los peces (@fig-migracion), lo cual lo hace especialmente vulnerables a las actividades de pesca sin manejo.

El conjunto de datos de los procesos sociales del MUF y FOCAL son regularmente sistematizados. A la fecha, la unidad de información de CIMA, cuenta con un registro actualizado de todos estos procesos. Esta información es continuamente solicitada por profesionales de CIMA y SERNANP para reportes y análisis correspondientes. La información es guardada y protegida en el servidor institucional de CIMA, junto con los verificables que acompañan la información, en carpetas organizadas por temáticas.

Se instaló la nueva estación meteorológica. Entre enero y marzo 2024, se ha concluido con la instalación de la nueva estación meteorológica ClimaVUETM 50; el cual, es un Sensor Meteorológico Digital Compacto.

Al primer trimestre, se tienen registradas 16 investigaciones que se ejecutan desde el 2022 y se encuentran en distintas etapas de desarrollo (@tbl-invest).

Se culminó la consultaría para medir los beneficios generados a las comunidades, en el marco del Fortalecimiento Organizacional de Capacidades Locales (FOCAL). De igual manera, se evaluó la efectividad de las intervenciones que CIMA, SERNANP realizan para apoyar el cumplimeinto de prioridades del Plan de Calidad de Vida, entre el 2008 - 2019. Para mostrar los detalles y resultados se ha elaborado un resumen ejecutivo.

### **Resultado 3**

En este trimestre se apoyó a las organizaciones a tramitar las solicitudes para los permisos de instalaciones de letreros orientativos e informativos, para los atractivos turísticos. Así también, informar sobre el flujo de turismo a los atractivo turístico de Río Azul y Catarata del Otorongo, ante la Municipalidad distrital de Pucayacu.

En el mes de febrero, se realizó una exploración desde el PVC 16 Chambirillo (SM) hasta el PVC 106 Boca Pauya (LO). El objetivo fue explorar esta ruta, para evaluar su potencial turístico, en el mediano y corto plazo. En el marco del desarrollo turístico, del sector Chambirillo. Se han identificado, 10 puntos de interés para observación de fauna y flora en el área, y se observaron huellas de Puma, Paujiles, Tortugas, Ronsocos, Sachavaca, Cóndor real.

Se realizaron capacitaciones en Turísmo Sostenible y Buenas prácticas de manipulación de alimentos. Como parte de las actividades programadas en el Plan de Acción, de la Asociación Laguna de los Encantos, en la sede Tocache.

Se inició el desarrollo del plan de trabajo de Turísmo 2024, para el Valle del Aspuzana. El cual, involucra la participación activa de la Municipalidad del distrito de Pucayacu, DIRCETUR-Tingo María, la Cooperativa Bioaltura y CIMA Cordillera Azul.

### **Resultado 4**

Se ha continuado con las actividades de Educación Ambiental No Formal (EANF). Así, 28 centros poblados participaron en distintas sesiones de aprendizaje, del manual de educación ambiental (@fig-eanf) , siendo un total de 759 personas, entre mujeres y varones (@fig-sexo_eanf).

Respecto de las normas de convivencia. Este trimestre, participaron 498 personas; 97 mujeres y 216 varones, de 10 centros poblados (@fig-NormasComunidades). El 23% de las comunidades concluyó con normas de convivencia, aprobadas en asamblea comunal (@fig-normas).

Se trabajaron los Plan de Calidad de Vida, de las comunidades nativas Shipibo Konibo Manco Capac y Kichwa Anak Kurutuyacu, y 16 centros poblados. Además, se viene realizando el seguimiento de las comunidades programadas para este año, según los sectores; Tarapoto (@fig-pvctarapoto), Tocache y Contamana (@fig-to_co_pcv). Además, se realizaron actividades para elaboración y actualización de PCV no programdos (@fig-noprogramados).

### **Resultado 5**

Acuerdos de Conservación en la sede Tocache. Este trimestre se elaboraron tres planes de trabajo, en el marco de los acuerdos de conservación con la cooperativa Agraria nueva visión LTDA, la Cooperativa de servicios especiales Bioaltura LTDA y a la Empresa cacaotera ARGE S.A.C.

A través del Fortalecimiento Organizacional Técnico Productivo (FOTP) se atendieron un total de 16 comunidades; nativas y centros poblados. En las comunidades que cuentan con PCV, se atendieron 14 comunidades; que representan 16 organizaciones; los cuales trabajan nueve distintos productos y servicios; como el café, cacao, artesanías y turismo, entre los más importantes. En este marco, se lograron concretar 21 hitos o logros, del trimestre (@tbl-fotp).

Se aprobaron tres fondos semillas, por un monto de 60 mil soles, cada uno. Además, se realizaron actividades de coordinación y apoyo técnico en la elaboración de 11 proyectos. Además, se ha concluído con la elaboración de cuatro proyecto, para los centros poblados de Consuelo, Bajo Chimbote, Inca Huasi y Lejía (@tbl-fs). Estos deben ser evaluados para su aprobación el siguiente trimestre.

Respecto de la inversión financiera en Kulkao, hasta el primer trimestre, abonó la suma total de US\$8,076.92 correspondiente al interés. Así también, la cuarta amortización de US\$46, 153.85 de los US\$600,000 prestados, por CIMA.

### **Resultado 6**

Se ha comercializado 4,325 VCUs por un valor de US\$25,582 autorizados con la carta N°0001-2024-SERNANP-J-SDG. De igual forma, esta pendiente por TOTALEnergies abonar los US\$10´000,000, previa evaluación de las actividades implementadas en la hoja de ruta.
